matrix:
  include:
  - language: python
    python:
    - '3.6'
    addons:
      apt:
        packages:
        - postgresql-server-dev-9.2
    services:
    - postgresql
    cache: pip
    install:
    - pip install -r backend/requirements.txt
    script:
    - cd backend
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    - pytest
    - pylint **/*.py
    - cd ..
    deploy:
      provider: script
      script: bash ./deploy.sh
      on: master
    before_install:
    - openssl aes-256-cbc -K $encrypted_2ac04bea7f82_key -iv $encrypted_2ac04bea7f82_iv
      -in .travis/deploy.key.enc -out .travis/deploy.key -d
    - chmod +x ./deploy.sh
    - eval "$(ssh-agent -s)"
    - chmod 600 .travis/deploy.key
    - ssh-add .travis/deploy.key
    - ssh-keyscan www.tentahjalpen.se >> ~/.ssh/known_hosts
    - git remote add dokku-backend dokku@www.tentahjalpen.se:tentahjalpen-backend
    - git config --global push.default simple

  - language: node_js
    node_js:
    - '11'
    cache: npm
    install:
    - cd frontend
    - npm install
    script:
    - cd ..
    - make test-front
